name: Application Deploy

on:
  push:
    branches: [main]

jobs:
  react-deploy:
    runs-on: ubuntu-18.04

    environment:
      name: prod

    env:
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_BUCKET_REGION: ${{ secrets.S3_BUCKET_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn
      
      - name: Build
        run: yarn build
      
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true